TweetrGeetr/Controllers/TweetController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using TweetrGeetr.Models;
using TweetrGeetr.ViewModels;
using static TweetrGeetr.Models.DataFixer;

namespace TweetrGeetr.Controllers
{
    public class TweetController : Controller
    {
        public  TweetRepository _tweetRepository;
        public CommentRepository _commentRepository;

        public TweetController(TweetRepository tweetRepository, CommentRepository commentRepository)
        {
            _tweetRepository = tweetRepository;
            _commentRepository = commentRepository;
        }
       
        [HttpGet]
        public async Task<IActionResult> Search(string searchQuery)
        {
            Char[] buffer;
            var badWordsList = new List<string>();
            using (var sr = new StreamReader("BadWords.txt"))
            {
                buffer = new Char[(int)sr.BaseStream.Length];
                await sr.ReadAsync(buffer, 0, (int)sr.BaseStream.Length);
            }
            var consolelog = new String(buffer);
            var splitWords = consolelog.Split("\r\n");
            badWordsList.AddRange(splitWords);

            if (badWordsList.Contains(searchQuery))
            {
                return View("~/Views/Shared/SearchExplicit.cshtml");
            }

            var url = "https://api.twitter.com/2/tweets/search/recent?query=" + searchQuery;
            var bearerAccessToken = "AAAAAAAAAAAAAAAAAAAAAMBHfQEAAAAA2cixCv%2BDTgF6qzQKdHW8LLtidY8%3DVbflRa4zCO3gQOpsxKK2WIuwZ08tRc1KkFgYLWFCkbn9Y7Y2ez";
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {bearerAccessToken}");
            var response = await httpClient.GetAsync(url);
            string jsonResponse = await response.Content.ReadAsStringAsync();
            var returnedTweets = JsonConvert.DeserializeObject<DataFixer.Root>(jsonResponse);
            var returnedArray = returnedTweets.data ?? new List<Datum>();
            List<Datum> TweetList = new List<Datum>();
            foreach (DataFixer.Datum tweet in returnedArray)
            {
                TweetList.Add(tweet);
            }
            
            _tweetRepository.AddTweetsToDb(TweetList);
            _tweetRepository._appDbContext.SaveChanges();
            ViewBag.SearchQuery = searchQuery;

            return View(TweetList);
        }

        public IActionResult BlogThis(string id)
        {
            var tweet = _tweetRepository.GetTweetById(id);
            if (tweet == null)
                return NotFound();

            return View(tweet);
        }

        public async Task<IActionResult> Success(string id, string addedComment)
        {
            Char[] buffer;
            var badWordsList = new List<string>();
            using (var sr = new StreamReader("BadWords.txt"))
            {
                buffer = new Char[(int)sr.BaseStream.Length];
                await sr.ReadAsync(buffer, 0, (int)sr.BaseStream.Length);
            }
            var consolelog = new String(buffer);
            var splitWords = consolelog.Split("\r\n");

            badWordsList.AddRange(splitWords);

            var splitCommentList = new List<string>();
            var splitCommentArray = addedComment.Split(" ");
            splitCommentList.AddRange(splitCommentArray);
            string expletiveFreeComment = "";

            foreach(string word in splitCommentList)
            {
                if (badWordsList.Contains(word))
                {
                    expletiveFreeComment += " ****";
                }
                else
                {
                    expletiveFreeComment += " " + word;
                }
            }

            var newComment = new BlogComment()
            {
                id = id,
                CommentContent = expletiveFreeComment,
                DateTimePosted = DateTime.Now
            };

            _commentRepository.AddCommentsToDb(newComment);
            _commentRepository._appDbContext.SaveChanges();
            var tweetToChangeStatus = _tweetRepository.GetTweetById(id);
            tweetToChangeStatus.isItBlogged = true;
            _tweetRepository._appDbContext.SaveChanges();
            var tweetToPass = _tweetRepository.GetTweetById(id);
            ViewBag.tweet = tweetToPass;

            return View(newComment);
        }
        
    }
}

TweetrGeetr/Views/Tweet/BlogThis.cshtml
<h1 class="display-2 m-5 font-weight-bold">New Blog</h1>
<h4 class="h1 m-5">Selected Tweet:</h4>
<partial name="_TweetCardNoButtons" model="@Model" />
<div id="add_comment_form" class="w-50 m-5">
    <form asp-controller="Tweet" asp-action="Success" asp-route-id="@Model.id" name="AddCommentForm">
        <div class="form-group">
            <label for="addedComment">Your Comment:</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="addedComment" required minlength="2" maxlength="300" pattern=".*\S+.*"></textarea>
            <button type="submit" class="btn btn-primary mt-3">Add Comment</button>
        </div>
    </form>
</div>

TweetrGeetr/Views/Tweet/Search.cshtml
@model List<TweetrGeetr.Models.DataFixer.Datum>

<h1 class="display-2 m-5 font-weight-bold">Search Results</h1>
<h4 class="h1 m-5">You searched for: <span class="text-primary">" @ViewBag.SearchQuery "</span></h4>

@if (Model.Count > 0)
{
    @foreach (var tweet in Model)
    {
        <partial name="_TweetCard" model="tweet" />
    }
}
else
{
        <div class="d-flex align-items-center justify-content-center vh-50">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Tweets not found.</p>
                <p class="lead">
                    Unfortunately there are no tweets matching your query.
                </p>
                <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Go Home</a>
            </div>
        </div>
}

TweetrGeetr/Views/Tweet/Success.cshtml
<partial name="_TweetCardNoButtons" model="@ViewBag.tweet" />

<h2 class=" h2 m-5 text-success"> Success!</h2>

<partial name="_CommentCardStart" model="@Model" />
<a asp-controller="home" asp-action="index">
    <button type="button" class="m-5 btn btn-outline-secondary btn-lg px-4">Go Home</button>
</a>